---
title: "Rings and Fields"
category: note
toc: true
---

Abstract algebra is apparently the study of rings and fields plus groups...

# Rings

::: {.callout-note title="Rings"}
Ring (German: Zahlring). A cycle of return. Sets that close back onto themselves on their operations.
:::

Rings are a set with addition and multiplication.

It's less restrictive than an algebra.
A ring only has to be closed over itself. 
That is, a closed set on addition and multiplication.
An algebra, on the other hand, always has to be defined **over something***. It has to be a vector space $A$ over $K$ equipped with a multiplication that is compatible with the scalars.

Algebra cares about basis and dimension.
Rings only care about "primeness" and factorization.

## Why rings?

Rings were first invented to solve Diophantine Equations.
**commutative algebra** is the study of rings.
Rings were invented as the concept of **ideals**.

Ideals are subsets of rings (technically called a sublattice, probably because it's a "discrete vector field" because it's a linear combination of the ring elements)

Ideals can be factored, and can be prime.

::: {.callout-note title="**What is an Ideal?**"}
An ideal $I$ is a subset of the ring that absorbs multiplication. If $r \in R$ and $x \in I$, then $rx \in I$. Notation: $(a, b)$ is the ideal generated by $a$ and $b$. It implies the set of all linear combinations $\{ra + sb \mid r, s \in R\}$.
:::

::: {.callout-note}
The Real ring $\mathbb{R}$ has exactly two ideals:
1. Zero ideal (0)
2. Entire ring (1)

It is trivial. This is because when trying to define any other ideal, say (0.001), you accidentally become the (1) ideal because you always have a multiplative inverse. 
:::

::: {.callout-note title="Maximal vs Prime Ideals"}
Maximal Ideal: An ideal $M$ is maximal if no other proper ideal $J$ contains $M$ (i.e., $M\subset J\subset R$ is impossible).
Prime Ideal: An ideal $P$ is prime if for any $a,b$ in the ring, if $ab\in P$, then $a\in P$ or $b\in P$
:::

## Function Ideals and Cotangent space

::: {.callout-important title="Essence"}
Linking Ideals and Geometry forms the power of abstract algebra
:::

> TODO: Fill in later.
### Quotient Notation 

$$R = \frac{\mathbb{R}[x,y]}{(y^2 - x^3)}$$
$$\text{Cotangent Space} = \frac{\mathfrak{m}}{\mathfrak{m}^2}$$
# Vector spaces

::: {.callout-note}
Vector spaces are
- Abelian Groups - sets closed under one operation that is associative, commutative, has an identity and inverses.
- Scalable by a Field - must be multipliable by some field that still keeps it closed.
:::

# Fields

A ring with division- that is, each element has a multiplicative inverse.
$ax=b$ is always solvable in a field.
$ax=b$ would be a diophantine equation if it's on the ring $\Bbb{Z}$, and can have no solutions (say, if $a$ and $b$ are coprime)

# Difference between Ring, Field and Algebra.

A ring is a set with addition and multiplication closed over itself.

A field is a commutative ring (ring with commutative multiplication) with an inverse defined for every non-zero element.
All fields are rings.

An algebra can be defined over a field or a ring. You need:
- To be "Over something" - Over a set with multiplication and addition (So at least a ring)
- Scalars that when multiplied to the elements, stays within the set.
- The scalars need not come from the "over" set.
Why need the scalars?
Scalars make it so that you can build all elements of the set from a few elements (a *basis*). This then gives access to the tools of linear algebra: determinants, traces, matrices, eigenstuff.

Nomenclature:

- Algebras over Rings are special Modules (+free, meaning it has a basis)
- Algebras over Fields are special Vector Spaces (+multiplication)

A few interesting things:

- A ring can be an algebra over itself. So is a field an algebra over itself. These are trivial though.